### ISSUE TITLE
Local discovery specs add broker port in the payload answer

### ISSUE THREAD

**Issue by Darcraytore1** [Panduza/panduza-doc#49]
We can currently get the ip address of the platform using the response message of the local discovery service, but the port currently obtained is the port of the local discovery service (53035), and not that of the broker we are looking for, so the response message must also contain the broker's port (or just suppose the port of the broker is always the 1883 in local)

**Comment by XdoctorwhoZ** [comment]
Good point, I will append broker port only (the platform will just have to send the one it uses to communicate when the local broker)

Maybe we should also append a requirement to say that if the platform is connected to a broker différent than "localhost" the LSD service should be disabled. What do you think @Darcraytore1  ?

**Comment by XdoctorwhoZ** [comment]
@wardru here is why I think you cannot connect after LSD process. 
What do you think about my propositions in the comment above?

**Comment by wardru** [comment]
About the port I agree that we should only show the broker's port (in the logs and in the app).

I don't understand your proposition @XdoctorwhoZ.
LDS works only with platforms that are connected on localhost? If so what does that mean? Because a platform connected on localhost might not be on the local network, it might not be connected to internet at all.
To me LDS just tells you on what computer the plateform is. It doesn't tell you if it's connected to a broker no?
If so do we care? Because my goal with LDS is just to find computers on a local network currently running a plateform no?

**Comment by wardru** [comment]
I'm still a bit confused with local discovery.

To me it was meant to find brokers in a local network, not platforms. So when you find a broker it can tell you what platforms it contains, and then you can create a connection to this broker to talk to these platforms

**Comment by wardru** [comment]
Dumb question:

What's the final purpose of LDS?
Ok you find computers running plateforms, but what  you really care about is connect to the brokers managing these platforms no?

I think there is a miscommunication with this image I posted, you guys seemed to agree with this approach:
https://cdn.discordapp.com/attachments/1233329966721011743/1234166756575285268/bitmap.png?ex=6638509c&is=6636ff1c&hm=20927013cfb2f16f51a28c0be296dc5d798c5ae68555c3e47477195258cfc098&

When we connect, we don't "add" platforms, we add connections to brokers. Then the broker tells you what platforms are there with a scan.

It has 2 advantages: you can identify computers on your network, and you can identify Panduza brokers on a network.
These are two very different things

PS: nitpick but I believe we just rename this feature LDS (local discovery service). First to avoid drug alusions and second because it's more coherent with what it is from a grammatical perspective.

**Comment by XdoctorwhoZ** [comment]
Décision 1: renaming into PLBD (Panduza Local Broker Discovery)

Definition proposition

Goal : finding brokers on the local network that are used for panduza purpose

So yes we are agreed on the fact that we want to find brokers on the network.

The current behavior of LSD is an ambiguous because it provides information about the platform and not the broker. But We assumed that the local broker is always in the same computer than the platform (which is true most of the time but false in the future)

**Comment by wardru** [comment]
I agree with these definitions!

But if you have 2 platforms on a local network that connect to the same broker it wouldn't work then because one of the platforms is not on localhost. That usecase would be for the future then? Because I have this need at my company. The broker will not be running on the same machine than the broker. Yet I think it would be very cool to demo that case.

Is it technically challenging for the platform to provide you with connection info? In my head it would be simple but it introduces a security/privacy issue.
This issue could easily be resolve with a `--hidden` flag at platform start to hide it from PLBD

**Comment by wardru** [comment]
These are just thoughts, for the MVP I'm also fine keeping it very simple: one platform/broker on 1 PC.
I just think that showing how platforms are just clients in the end and how they are independant from brokers when it comes to network shows a strong part of Panduza. It's a modular and flexible web of clients wherever you want.

**Comment by XdoctorwhoZ** [comment]
> I agree with these definitions!
> 
> But if you have 2 platforms on a local network that connect to the same broker it wouldn't work then because one of the platforms is not on localhost. That usecase would be for the future then? Because I have this need at my company. The broker will not be running on the same machine than the broker. Yet I think it would be very cool to demo that case.
> 
> Is it technically challenging for the platform to provide you with connection info? In my head it would be simple but it introduces a security/privacy issue. This issue could easily be resolve with a `--hidden` flag at platform start to hide it from PLBD

I think the simple solution is, if the platform connection host/addr is localhost PLBD is active else PLBD is disabled. That way only the platform which holds the broker will answer.

The only case it can be a problem is when the user will have multiple platforms on its local network and a broker on a machine that have no platform (usecase very unlikely because in this case, it would probably go to cloud solution)

Of course, this solution will probably evolve later because users use case will surprise us

**Comment by Darcraytore1** [comment]
> > I agree with these definitions!
> > But if you have 2 platforms on a local network that connect to the same broker it wouldn't work then because one of the platforms is not on localhost. That usecase would be for the future then? Because I have this need at my company. The broker will not be running on the same machine than the broker. Yet I think it would be very cool to demo that case.
> > Is it technically challenging for the platform to provide you with connection info? In my head it would be simple but it introduces a security/privacy issue. This issue could easily be resolve with a `--hidden` flag at platform start to hide it from PLBD
> 
> I think the simple solution is, if the platform connection host/addr is localhost PLBD is active else PLBD is disabled. That way only the platform which holds the broker will answer.
> 
> The only case it can be a problem is when the user will have multiple platforms on its local network and a broker on a machine that have no platform (usecase very unlikely because in this case, it would probably go to cloud solution)
> 
> Of course, this solution will probably evolve later because users use case will surprise us

I'm not sure to understand the reason why it would be a problem to diffuse the addr/port of a broker with PLBD if the broker is not running on the same machine than the platform. 

If 2 platform are using the same broker on a local network, these 2 platform can send the addr/port of the broker they are using without problems.

If 2 platforms are running on the same machine, the 2 platform run the PLBD on the same port, so if we want to manage this case, we need change the port each time it would be used. 

I think the solution of Antoine would be better to use for example a flag --hidden to not use the service if you are looking for privacy because I think your solution Xavier would just limit the freedom of a user who would for example have his platform on a different machine than the broker but didn't care of privacy.

**Comment by XdoctorwhoZ** [comment]
> If 2 platform are using the same broker on a local network, these 2 platform can send the addr/port of the broker they are using without problems.

I'm not against this idea. How would you do this ? The platform sends information contained in the connection.json file addr/port?

I don't like the idea of the --hiden. I prefer a more automatic solution, else a large part of users won't do it when they will go on cloud (and will complain about it).
Is there a way to find if a given adresse is from local network or not?

**Comment by Darcraytore1** [comment]
Yeah, you could do this by reading the network.json file, or when you create a connection with the broker, you could record the connection info and give it back when you make a discovery request.

The --hidden flag would only be used for self-managed brokers, otherwise the cloud's basic behavior would include this function without specifying the flag, it's pretty easy to make a different comportement for this cloud connections.

Yes, it's possible to check if an address is on our local network using ping and arp cache, but I'm not sure about the security constraints behind it.

**Comment by XdoctorwhoZ** [comment]
Ok, this is a note for me.
I need to propose a specification to summarize this conversation.

**Comment by wardru** [comment]
FYI you cannot get this info by reading the `network.json` file @Darcraytore1.
Based on the requirements, this file is optional. But I agree with the second approach.

**Comment by wardru** [comment]
@XdoctorwhoZ The `--hiden` flag was just an idea so that the person that creates the platform gets the chance to hide it from PLBD. It wouldn't be there by default
